made changes to main and info screens
littlecreep0/MyFavouritePokemons pull request #2
Opened 2024-06-18 18:32 UTC by littlecreep0

- Made changes to main and info screens:
   - now 100% match-parent free,
   - main screen now has icons yay,
   - the text is now a bit bigger,
   - type info is now colored.
- Remade null pointer exception protection (again)
- However, if something - somehow - against all odds - goes wrong, a wild MissingNo will appear...
   (im not willing to throw an exception, ill throw another pokemon to catch instead)

Screenshots:
![Screenshot_20240618-211935](https://github.com/littlecreep0/MyFavouritePokemons/assets/124192249/0973403d-95b0-4539-a873-dc03302c7839)
![Screenshot_20240618-211940](https://github.com/littlecreep0/MyFavouritePokemons/assets/124192249/2ad96ff7-b82d-4a63-a1a1-a0a6bea3699c)
![Screenshot_20240618-212237](https://github.com/littlecreep0/MyFavouritePokemons/assets/124192249/0652b35d-73d4-48c3-b757-d6250a37f837)

2024-06-18 21:11 UTC, pzinkevich42innowise commented
Название feature-ветки должно начинаться с префикса feature/...

2024-06-18 21:22 UTC, pzinkevich42innowise requested changes

2024-06-18 21:22 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/PokemonAbout.kt
> +        val pokemonPicture: ImageView = binding.pokemonPicture
можно и убрать, смысла в этом немного

2024-06-18 21:22 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/PokemonAbout.kt
> +                pokemonType.setTextColor(resources.getColor(R.color.normal))
А если добавится ещё одно поле, будет ещё 9 строчек копипасты? А если два поля, 18? Кажется, с этим кодом что-то не так

2024-06-18 21:22 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/PokemonList.kt
>          }
Опять то же самое. Для унификации был метод showPokemonInfo, но потом всё равно дублируется код вокруг неё. Давай учиться абстракции. Можно сделать общую функцию настройки вьюшек, в неё передать вьюшки и необходимые данные, и внутри уже одинаковым образом всё настраивать

2024-06-18 21:22 UTC, pzinkevich42innowise commented on app/src/main/res/drawable/missingno.png
Выглядит конечно крипово, но почему бы и да)))

2024-06-19 10:49 UTC, littlecreep0 commented on app/src/main/res/drawable/missingno.png
это замечание или зачёт?

2024-06-19 10:50 UTC, littlecreep0 commented
Переименование ветки потребует автозакрытия и создания нового ПР - что на мой взгляд намного хуже, чем недописанное название ветки; пересоздавать не буду, но запомню

2024-06-19 19:53 UTC, pzinkevich42innowise requested changes

2024-06-19 19:53 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/PokemonList.kt
> +        imageViewInit()
Получилось не лучше

Я имел в виду функцию типа:

fun setupPokemon(textView: TextView, imageView: ImageView, name...) {
textView.setOnClick 
imageView.setOnClick
}

И использовать её типа
setupPokemon(eevee, eeveeImage, "Eevee" ...)

2024-06-21 04:38 UTC, pzinkevich42innowise approved these changes

2024-06-21 04:38 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/PokemonList.kt
> +                               height: String, weight: String, @DrawableRes image: Int){
обычно каждый аргумент на новой строчке

2024-06-21 07:28 UTC, merged