remade the main screen using recycler view
littlecreep0/MyFavouritePokemons pull request #3
Opened 2024-06-21 16:48 UTC by littlecreep0

- Recreated pokemon list screen, now uses Recycler View with image-text items instead of fixed image-text strings
  (this bad boy can fit so many sylveons)
- Additions to the list are made using PokemonRepo class
  (guess i was the last to add Pokemon and PokemonRepo class c: )
- Items are separated with custom-made divider; updated with custom-made DiffUtil function
- Classes are now stored in related folders

Screenshots:
![Screenshot_20240621-191622](https://github.com/littlecreep0/MyFavouritePokemons/assets/124192249/f9c5a021-0793-4679-9e40-314f44074bc5)

![Screenshot_20240621-190211](https://github.com/littlecreep0/MyFavouritePokemons/assets/124192249/9bb5a47f-ab0f-4660-b752-3873f9ee802c)
(its all sylveons... maybe)

2024-06-23 19:27 UTC, pzinkevich42innowise requested changes

2024-06-23 19:27 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/recyclerViewSetup/CustomDivider.kt
> +class CustomDivider(private val dividerDrawable: Drawable) : RecyclerView.ItemDecoration() {
А дефолтный чем не устроил?

2024-06-23 19:27 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/recyclerViewSetup/DiffUtilCallback.kt
> +                && oldPokemon.image == newPokemon.image
А разве нет альтернатив? Ты используешь data class, кажется он это умеет

2024-06-23 19:27 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/ui/PokemonList.kt
> +        val pokemonList = PokemonRepo.getPokemonList().values.toList()
С точки зрения SOLID не совсем верно, что мы знаем способ хранения данных, и к тому же как-то манипулируем ими в классе, отвечающим за отображение данных

2024-06-23 19:27 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/ui/PokemonList.kt
> +        adapter.onClick = { pokemon ->
Я бы сначала полностью настроил адаптер, а потом уже пихал в него какие-то данные

2024-06-23 19:27 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/ui/PokemonList.kt
> +            putExtra("PokemonType", type) //<-- this becomes android.content.Intent.getType()
Ты всегда можешь использовать код без операторов with и apply ))

2024-06-24 07:10 UTC, littlecreep0 commented on app/src/main/java/lc/wise/myfavouritepokemons/recyclerViewSetup/CustomDivider.kt
> +class CustomDivider(private val dividerDrawable: Drawable) : RecyclerView.ItemDecoration() {
вставляет сепаратор после последнего элемента, где отделять уже нечего

2024-06-24 07:22 UTC, pzinkevich42innowise requested changes

2024-06-24 07:22 UTC, pzinkevich42innowise commented on app/src/main/java/lc/wise/myfavouritepokemons/recyclerViewSetup/CustomDivider.kt
> +class CustomDivider(private val dividerDrawable: Drawable) : RecyclerView.ItemDecoration() {
Это странно, потому что он так делать не должен. В любом случае использовать надо его, а не писать свой

2024-06-24 07:48 UTC, littlecreep0 commented
собственно, дефолтный разделитель

![Screenshot_20240624-104205.png](https://github.com/littlecreep0/MyFavouritePokemons/assets/124192249/843a401e-f7e7-435d-aebd-118173708e67)

против кастомного

![Screenshot_20240624-104115.png](https://github.com/littlecreep0/MyFavouritePokemons/assets/124192249/b03a767c-e1c0-4aa1-a050-fc1c6412541d)

примерно поэтому я кастомный и писал

2024-06-24 08:13 UTC, pzinkevich42innowise approved these changes

2024-06-24 08:15 UTC, merged